apiVersion: v1
kind: Pod
metadata:
  name: mig-mixed-vectoradd
  namespace: default
spec:
  restartPolicy: Never
  containers:
    - name: cuda-test
      image: nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda12.5.0-ubuntu22.04
      resources:
        limits:
          nvidia.com/mig-2g.10gb: 1
